CREATE USER 'root'@'localhost' IDENTIFIED BY 'password';

DROP TABLE IF EXISTS EMPLOYEE;
 
CREATE TABLE EMPLOYEE (
  EMPLOYEE_ID INT PRIMARY KEY,
  EMPLOYEE_NAME VARCHAR(250) NOT NULL,
  TITLE VARCHAR(250) NOT NULL,
  BUSINESS_UNIT VARCHAR(250) NOT NULL,
  PLACE VARCHAR(250) NOT NULL,
  SUPERVISOR_ID INT NOT NULL,
  COMPETENCIES VARCHAR(250) NOT NULL,
  SALARY INT NOT NULL
);
 
INSERT INTO EMPLOYEE () VALUES
  ('1', 'AAA', 'Dev','AB','India',33,'A1',500000),
  ('2', 'BBB', 'Test','CD','USA',22,'B1',600000),
  ('3', 'CCC', 'Dev','AB','UK',1,C1,900000);